### PR TITLE
Add Send email/sms with Novu community plugin

### PR DESCRIPTION
**Pull request by intertwine**
Use Connery to trigger email and sms workflows using the open source Novu messaging platform.

### CODE REVIEW

**Comment by machulav** [comment]
@intertwine Thank you for the contribution! 

How is your experience with Connery Runner and plugin development?

**Comment by intertwine** [comment]
Thanks @machulav! I think Connery Runner is really useful and I'm glad to see it picked up by Langchain and elsewhere. Lots of nice developer experience touches, like the `create app` and `create plugin` scripts. Would love to see you guys open source a version of your Slack client as well, could get good adoption for enterprises. I'll be adding more plugins over time

**Comment by machulav** [comment]
@intertwine, thank you for the feedback! I'm glad that it works for you.

Which use cases do you see for the open-sourced Slack client? Can't it be used as it is now, hosted by us? You can still connect to your runner.

**Comment by intertwine** [comment]
Sure, I think it can be used as is, and it will be if you can get people to pay attention to you; but from my point of view as a developer of larger solutions for enterprise customers, you're going to build more developer trust and get broader distribution if you make your clients and server as open as possible (like you've already done with the runner and the plugin maker), and make your investment back by charging folks to host the runners and make it as easy as possible to get spun up, connect clients and tools. That way I can build whatever I want on your platform and you can charge me to make it easy. AND I can share back improvements to make the whole ecosystem better. Look at Supabase as a company that does this model well (and does very well by doing it).  So that's my vote for open source slack client — bottom line, I like the platform you've built, but the more open source you make it, the more I can trust (and control) building it into my own apps.

**Comment by machulav** [comment]
@intertwine, you're absolutely right, and I really appreciate your perspective! Embracing the philosophy of openness is at the core of what we do. You make a great point about open-sourcing the Slack app. Honestly, it hasn't been our primary focus, which is why we haven't invested much time in that. However, you're already the second person interested in open-sourcing it, so we will seriously consider it.

I am also glad that you mention Supabase - they do an excellent job, and we're very inspired by them! Fun fact: our Slack app actually leverages Supabase for data storage 🙂

Thanks again for your valuable feedback, which helps us grow and improve!

**Pull request merged**
